---

- name: Get vector distrib
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: "https://yum.vector.dev/stable/vector-0/x86_64/vector-{{ vector_rpm_version }}.x86_64.rpm"
    dest: "./vector-{{ vector_rpm_version }}.x86_64.rpm"
    mode: "0755"
  with_items: "{{ vector_version }}"
