---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: almalinux8
#    image: bviktor/ansible-systemd-almalinux:8
    image: ghcr.io/hifis-net/almalinux-systemd:9
    pre_build_image: true
  - name: almalinux9
    image: ghcr.io/hifis-net/almalinux-systemd:9
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
