---
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: rockylinux8
#    image: quay.io/centos/centos:stream9
    image: nmusatti/rockylinux8-pys-systemd
    pre_build_image: true
  - name: fedora
#    image: quay.io/centos/centos:stream9
    image: fedora-pys-systemd
    pre_build_image: true

#  - name: oraclelinux-8
#    image: oraclelinux:8
#    systemd: always
#    command: ${MOLECULE_DOCKER_COMMAND:-""}
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:rw
#    cgroupns_mode: host
#    privileged: true
#    pre_build_image: true
#  - name: ubuntu-latest
#    image: ubuntu
#    systemd: always
#    command: ${MOLECULE_DOCKER_COMMAND:-""}
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:rw
#    cgroupns_mode: host
#    privileged: true
#    pre_build_image: true
provisioner:
  name: ansible
#  env:
#    ANSIBLE_LOCAL_TEMP: "${WORKSPACE:-$HOME}/.ansible/tmp"
#    ANSIBLE_REMOTE_TMP: /tmp
verifier:
  name: ansible
#role_name_check: 1
