---
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: almalinux8
    image: bviktor/ansible-systemd-almalinux:8
    pre_build_image: true
  - name: almalinux-9
    image: bviktor/ansible-systemd-almalinux:9
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
