---

driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: AlmaLinux-8
    image: ghcr.io/bpadair32/docker-image-alma8-systemd:latest
    pre_build_image: true
  - name: AlmaLinux-9
    image: ghcr.io/bpadair32/docker-image-alma9-systemd:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
