---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: oraclelinux-8
    image: oraclelinux:8
    systemd: always
    pre_build_image: true
  - name: ubuntu-latest
    image: ubuntu
    systemd: always
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_LOCAL_TEMP: "${WORKSPACE:-$HOME}/.ansible/tmp"
    ANSIBLE_REMOTE_TMP: /tmp
verifier:
  name: ansible
role_name_check: 1
