---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: oraclelinux-8
    image: oraclelinux:8
    pre_build_image: true
    privileged: true
  - name: ubuntu-latest
    image: ubuntu:latest
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
role_name_check: 1
