---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: centos8
    image: docker.io/pycontribs/centos8
    pre_build_image: true
#  - name: almalinux8
#    image: bviktor/ansible-systemd-almalinux:8
#    pre_build_image: true
#  - name: almalinux9
#    image: bviktor/ansible-systemd-almalinux:9
#    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
