---

driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
#  - name: rockylinux-9
#    image: nmusatti/rockylinux9-pys-systemd
#    pre_build_image: true
  - name: centos-stream-9
#    image: nmusatti/centos-stream9-pys-systemd
    image: ghcr.io/hifis-net/almalinux-systemd:8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
