---
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
#  - name: rockylinux-8
#    image: nmusatti/rockylinux8-pys-systemd
#    pre_build_image: true
  - name: centos-stream-8
    image: nmusatti/centos-stream8-pys-systemd
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
