---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: almalinux8
    image: ghcr.io/hifis-net/almalinux-systemd:8
    pre_build_image: true
#  - name: almalinux9
#    image: ghcr.io/hifis-net/almalinux-systemd:9
#    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
