---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Vector launched
    assert:
      that:
        - vector_run.failed == false
      success_msg: "/Vector lanched"
      fail_msg: "/Vector not launched"