---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Exist vector.conf
      ansible.builtin.find:
        paths: /opt/vector-x86_64-unknown-linux-musl/config
        patterns: 'vector.yaml'
      register: vector_conf

    - debug:
        var:
          vector_conf

#  - name: Vector launched
#    assert:
#      that:
#        - vector_run.failed == false
#      success_msg: "Vector lanched"
#      fail_msg: "Vector not launched"