---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Vector config find
      ansible.builtin.find:
        paths: /opt/vector-x86_64-unknown-linux-musl/config
        patterns: 'vector.yaml'
      register: vector_conf

#    - debug:
#        var:
#          vector_conf

  - name: Vector config
    assert:
      that:
        - vector_conf.failed == false
      success_msg: "Vector config exists"
      fail_msg: "Vector config no exists

#  - name: Vector launched
#    assert:
#      that:
#        - vector_run.failed == false
#      success_msg: "Vector lanched"
#      fail_msg: "Vector not launched"