---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu_latest
    image: geerlingguy/docker-ubuntu2404-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converage
    - destroy
