---
driver:
  name: podman
platforms:
  - name: almalinux9
    image: ghcr.io/hifis-net/almalinux-systemd:9
    pre_build_image: true
scenario:
  test_sequence:
    - destroy
    - create
    - converage
    - destroy
