---
driver:
  name: podman
platforms:
  - name: almalinux9
    image: bviktor/ansible-systemd-almalinux:9
    pre_build_image: true
scenario:
  test_sequence:
    - destroy
    - create
    - converage
    - destroy
